GET http://localhost:1100/users

###

POST http://localhost:1100/users
Content-Type: application/json

{
    "name": "Messi",
    "password": "pass"
}

###
POST http://localhost:1100/users/login
Content-Type: application/json

{
    "name": "Messi",
    "password": "pass"
}


###
POST http://localhost:1100/api/users/register
Content-Type: application/json

{
    "name": "user1",
    "email": "pass@qwe",
    "password": "asd2"
}

###
POST http://localhost:1100/api/users/login
Content-Type: application/json

{
    "name": "Messi1",
    "email": "pass@qwe",
    "password": "asd2"
}

###
POST http://localhost:1100/api/notes/create
Content-Type: application/json

{
   "user":
   {
      "_id":"6423630f8d24a8c1ceadcfdb",
      "name":"Messi1",
      "email":"pass@qwe",
      "password":"$2a$10$hveMhq0QMbTHfKEd1O5uWewb6Ti4NoDJvThCtWNc.xd1h./tyS.uO"
   },
   "title":"TEST NOTE",
   "content":"content note",
   "category":"category note"
}
### 
GET http://localhost:1100/api/notes/getnotes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0M2ViYmFkNGIxZWY0MmJkZDAxZmRlZCIsImlhdCI6MTY4MTgzMzQyMiwiZXhwIjoxNjg0NDI1NDIyfQ.HCdFhMgBSMpcn_pXhiN4WJ9qi0bZ5V6oB3CXEoMG9Ag

{
    "user":{
        "_id": "643ebbad4b1ef42bdd01fded",
        "email": "pass@qwe1",
        "password": "asd123"
    }    
}

###
POST http://localhost:1100/api/notes/create
Content-Type: application/json

{
   "user":
   {
      "_id":"643ebbad4b1ef42bdd01fded",
      "name":"user1",
      "email":"pass@qwe1",
      "password":"asd123"
   },
    "title": "Started React JS",
    "content": "Made my first App in React JS, feels awesome to learn something new. I aim to be a full stack dev someday",
    "category": "Learning"
}

###
POST http://localhost:1100/api/notes/create-search-notes
Content-Type: application/json

{
  "_id": "643ebc494b1ef42bdd01fdef",
  "title": "usefull title notes",
  "content": "usefull title content",
  "category": "usefull category",
  "user": "643ebbad4b1ef42bdd01fded"
}





